## Contents

- How To Ask For Help
- How to make numpy Arrays
- Array math
- How to subset, slice, and index arrays
- How to manipulate arrays

### How to Ask for Help

In [0]:
import numpy as np
# Look up info on `mean` with `np.lookfor()`
print(np.lookfor('mean'))

Search results for 'mean'
-------------------------
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.array_equiv
    Returns True if input arrays are shape consistent and all elements equal.
numpy.matrix.mean
    Returns the average of the matrix elements along the given axis.
numpy.chararray.mean
    Returns the average of the array elements along given axis.
numpy.ma.anom
    Compute the anomalies (deviations from the arithmetic mean)
numpy.ma.fix_invalid
    Return input with invalid data masked and replaced by a fill value.
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.pad
    Pads an array.
numpy.put
    Replaces specified elements of an array with given values.
numpy.std
    Compute the standard deviation along the specified axis.
numpy.sum
    Sum of array

In [0]:
# Get info on data types with `np.info()`
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### How to make numpy arrays

In [0]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[1 2 3]
int32
1
(3,)
3


In [0]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)
# Change the data type of `my_array`
b.astype(float)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
c = np.array([x for x in range(10)],dtype=np.int64)
print(c)
print(c.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [0]:
d = np.array([x for x in range(10)],dtype=np.float)
print(d)
print(d.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [0]:
# Create an array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [0]:
# Create an array with random values
np.random.random((2,2))

array([[0.2879652 , 0.15831094],
       [0.55429166, 0.48372932]])

In [0]:
# Create an empty array
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [0]:
# Create a full array
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [0]:
# Create an array of evenly-spaced values
np.arange(10,25,5)

array([10, 15, 20])

In [0]:
# Create an array of evenly-spaced values
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
np.eye(10)
# or np.identity(10)


array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### Array math

In [0]:
b = np.array([[1,2,3],[4,5,6]])
b + 1
b - 2
b * 3
b / 2
b % 2
# 
# np.add(b,1)
# np.subtract(b,2)
# np.multiply(b,3)
# np.divide(b,2)
# np.remainder(b,2)
# np.exp()
# np.sqrt()
# np.sin()
# np.cos() 
# np.log()

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [0]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
np.dot(a,b)

40

In [0]:
a = np.array([1,2,3,4])
a.sum() # Array-wise sum
a.min() # Array-wise minimum value
b = np.array([[5,12,7],[8,9,10]])
b.max(axis=0) # result is an array with column maxima 
b.max(axis=1) # result is an array with row    maxima
b.cumsum(axis=1) # cumulative sum of the elements by row
b.cumsum(axis=0) # cumulative sum of the elements by column
a.mean() # Mean
np.median(a) # Median of all elements
np.median(b, axis=1) # Medians of rows
np.corrcoef(a) # Correlation coefficient
np.std(b, axis=1) # Standard deviations of rows

array([2.94392029, 0.81649658])

### How to subset, slice, and index arrays

#### In general, the following holds:
a[start:end] # elements from start to end (not including end)
a[start:] # all elements from start
a[:end] # elements from start to end (not including end)
a[:] # all elements

In [0]:
# indexing individual elements
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b[0,0])
print(b[1,2])
# slicing arrays
print(b[1,:]) # just the second row
print(b[:,2]) # just the second column
# 

1
7
[5 6 7 8]
[ 3  7 11]


In [0]:
# logical indexing
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
selection = b<10
print(selection) 
print(b[selection])
print(b*selection)
# logical indexing can be used to select a subset of rows based on elements in a column fullfilling a criterium
c = np.random.random((4,5))
# print(c)
sel = c[:,1]<0.5
print(c[sel,:])


[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4]
 [5 6 7 8]
 [9 0 0 0]]
[[0.35931506 0.08800478 0.7295676  0.88104993 0.04126388]
 [0.17486776 0.42009741 0.34060658 0.04476892 0.11289131]
 [0.43804149 0.0710732  0.81624511 0.86611565 0.13111984]]


In [0]:
# advanced indexing
# to change the order of the columns:
print(b[:,[2,0,1]])


[[ 3  1  2]
 [ 7  5  6]
 [11  9 10]]


### How to manipulate arrays

#### Advice: do not use the reshape, resize, insert and delete functions

In [0]:
b = np.array([[1,2,3],[4,5,6]])
np.transpose(b)
# korter:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
b=b.reshape(3,2) # this is tricky - don't use ...
print(b)
b.ravel() # changes to one dimension

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

In [0]:
b = np.array([[1,2,3],[4,5,6]])
np.append(b,[[21,22,23]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [21, 22, 23]])

In [0]:
b = np.array([[1,2,3],[4,5,6]])
b = np.insert(b,[1],[33,34])
np.reshape(b,(2,4))

[ 1 33 34  2  3  4  5  6]


array([[ 1, 33, 34,  2],
       [ 3,  4,  5,  6]])

In [0]:
b = np.array([[1,2,3],[4,5,6]])
np.delete(b,4)

array([1, 2, 3, 4, 6])

In [0]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[8,9,10],[11,12,13]])
x = np.array([20,21,22])

# Concatentate a and x
print(np.concatenate((a,x)))

# Stack arrays row-wise
bx = np.vstack((b,x))
print(bx)

# select first two rows
print(bx[0:2,:])

# Stack arrays column-wise
bc = np.hstack((b,c))
print(bc)

# select first two columns
print(bc[:,0:2])


[ 1  2  3 20 21 22]
[[ 1  2  3]
 [ 4  5  6]
 [20 21 22]]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3  8  9 10]
 [ 4  5  6 11 12 13]]
[[1 2]
 [4 5]]
